title: Sztandarscy
subtitle: "Pokoje w Łebie i Domek w Sarbsku"
repository: lakistech/sztandarscy.pl
name: "lakis.tech"

locale: "pl-PL"

email: elzuniasz@op.pl

description: >-
  Elżbieta i Ireneusz Sztandarscy - 
  Pokoje w Łebie i Domek w Sarbsku
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nowa.sztandarscy.pl" # the base hostname & protocol for your site, e.g. http://example.com

teaser: /assets/images/500x300.png
og_image: /img/sarbsk01.jpg
atom_feed:
  hide: true

# Build settings
include: ["_pages"]
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
