title: Sztandarscy
email: elzuniasz@op.pl
description: >-
  Pokoje w Łebie i Domek w Sarbsku
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nowa.sztandarscy.pl" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
